import type { UserProfile } from "@/types/profile"

export const defaultProfile: UserProfile = {
  name: "",
  title: "",
  bio: "",
  location: "",
  portfolio: "",
  github: "",
  twitter: "",
  linkedin: "",
  devto: "",
  medium: "",
  wakatime: "",
  skills: [],
  enabledComponents: {
    header: true,
    about: true,
    skills: true,
    stats: true,
    streak: true,
    topLangs: true,
    wakatime: false,
    blog: false,
    social: true,
    visitors: true,
    support: false,
    trophies: false,
    activity: false,
    addons: false,
  },
  template: "minimalist",
  theme: "light",
  customization: {
    fontFamily: "sans",
    cardStyle: "flat",
    iconSet: "simple",
    statsTheme: "default",
    skillsLayout: "grid",
  },
  work: {
    company: "",
    position: "",
    website: "",
    startDate: "",
    endDate: "",
    current: true,
  },
  education: {
    institution: "",
    degree: "",
    field: "",
    startDate: "",
    endDate: "",
    current: false,
  },
  additionalInfo: {
    currentLearning: [],
    collaborateOn: "",
    helpWith: "",
    askMeAbout: [],
    funFact: "",
    pronouns: "",
  },
  socialLinks: {
    codepen: "",
    stackoverflow: "",
    kaggle: "",
    instagram: "",
    dribbble: "",
    behance: "",
    hashnode: "",
    youtube: "",
    codechef: "",
    hackerrank: "",
    codeforces: "",
    leetcode: "",
    topcoder: "",
    hackerearth: "",
    geeksforgeeks: "",
    discord: "",
    rss: "",
  },
  supportLinks: {
    buymeacoffee: "",
    patreon: "",
    kofi: "",
    paypal: "",
  },
  displayOptions: {
    showTitleFirst: false,
    showVisitorsBadge: true,
    showGitHubBadge: true,
    showWorkExperience: false,
    showEducation: false,
    showBlogPosts: false,
    showSkillIcons: true,
    showSocialIcons: true,
    showSupportSection: false,
    showTrophies: false,
    showActivityGraph: false,
  },
}
